# Generated by Django 4.0.3 on 2024-02-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0005_rename_first_name_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Members'},
        ),
    ]
