# Generated by Django 4.0.3 on 2024-02-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0006_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
