# Generated by Django 4.0.3 on 2024-02-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0007_alter_employee_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Member',
        ),
    ]
